# Generated by Django 4.1 on 2022-11-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_allpost_liked_by_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='likes',
        ),
    ]
