# Generated by Django 4.1 on 2023-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='launch_date',
            field=models.DateTimeField(null=True),
        ),
    ]
