# Generated by Django 4.1 on 2023-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0003_game_launch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='launch_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(upload_to='potbs/static/potbs'),
        ),
    ]
