# Generated by Django 4.1 on 2023-01-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0004_alter_game_launch_date_alter_game_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
