# Generated by Django 4.1 on 2023-01-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0005_rename_thumbnail_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='potbs/static/potbs/space_dog.png')),
                ('username', models.CharField(max_length=64)),
                ('skills', models.CharField(max_length=64)),
                ('social_media', models.URLField()),
                ('bio', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/potbs'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sub_title',
            field=models.TextField(blank=True),
        ),
    ]
