# Generated by Django 4.1 on 2023-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0006_team_alter_game_description_alter_game_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='social_media',
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='itch_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
