# Generated by Django 4.1 on 2023-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0007_remove_team_social_media_team_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
