# Generated by Django 4.1 on 2023-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0009_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='itch_profile',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.AddField(
            model_name='team',
            name='itch',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
