# Generated by Django 4.1 on 2023-01-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0010_remove_team_itch_profile_remove_team_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='itch',
            new_name='itch_profile',
        ),
    ]
