# Generated by Django 4.1 on 2023-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0011_rename_itch_team_itch_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
