# Generated by Django 4.1 on 2023-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0013_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_poster', models.ImageField(blank=True, upload_to='images')),
                ('event_name', models.CharField(max_length=64)),
                ('event_description', models.TextField(blank=True)),
                ('event_date', models.DateField(null=True)),
                ('event_country', models.CharField(max_length=64)),
                ('event_city', models.CharField(max_length=64)),
                ('map_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
