# Generated by Django 4.1 on 2023-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0014_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(null=True),
        ),
    ]
