# Generated by Django 4.1 on 2023-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0016_remove_event_event_time_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
