# Generated by Django 4.1 on 2023-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0018_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
