# Generated by Django 4.1 on 2023-05-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0019_alter_event_event_poster_alter_game_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ImageField(blank=True, upload_to='')),
                ('genre', models.CharField(choices=[('INT', 'Interactive Story'), ('PAC', 'Point & Click'), ('PLT', 'Platformer'), ('PZL', 'Puzzle'), ('RPG', 'RPG'), ('SIM', 'Simulation')], max_length=3)),
                ('bg_image', models.ImageField(blank=True, upload_to='')),
                ('music_genre', models.CharField(choices=[('EBT', '8-bit'), ('AMB', 'Ambient'), ('ELC', 'Electronic'), ('FLK', 'Folk'), ('ORC', 'Orchestral'), ('SYT', 'Synthwave')], max_length=3)),
                ('voice_acting', models.BooleanField(null=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
