# Generated by Django 4.1 on 2023-05-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0020_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='genre',
            field=models.CharField(blank=True, choices=[('INT', 'Interactive Story'), ('PAC', 'Point & Click'), ('PLT', 'Platformer'), ('PZL', 'Puzzle'), ('RPG', 'RPG'), ('SIM', 'Simulation')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vote',
            name='music_genre',
            field=models.CharField(blank=True, choices=[('EBT', '8-bit'), ('AMB', 'Ambient'), ('ELC', 'Electronic'), ('FLK', 'Folk'), ('ORC', 'Orchestral'), ('SYT', 'Synthwave')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
