# Generated by Django 4.1 on 2023-05-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0022_alter_vote_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Idea',
        ),
    ]
