# Generated by Django 4.1 on 2023-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0023_rename_vote_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='genre',
            field=models.CharField(blank=True, choices=[('Interactive Story', 'Interactive Story'), ('Platformer', 'Platformer'), ('Point & Click', 'Point & Click'), ('Puzzle', 'Puzzle'), ('RPG', 'RPG'), ('Simulation', 'Simulation')], max_length=64),
        ),
        migrations.AlterField(
            model_name='idea',
            name='music_genre',
            field=models.CharField(blank=True, choices=[('8-bit', '8-bit'), ('Ambient', 'Ambient'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Orchestral', 'Orchestral'), ('Synthwave', 'Synthwave')], max_length=64),
        ),
    ]
