# Generated by Django 4.1 on 2023-05-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0024_alter_idea_genre_alter_idea_music_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='vote',
        ),
        migrations.AddField(
            model_name='idea',
            name='voted_by',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
