# Generated by Django 4.1 on 2023-05-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0027_remove_idea_voted_by_idea_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='votes',
        ),
        migrations.AddField(
            model_name='idea',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
