# Generated by Django 4.1 on 2023-05-15 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0028_remove_idea_votes_idea_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='vote',
        ),
        migrations.AddField(
            model_name='idea',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
