# Generated by Django 4.1 on 2023-05-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0029_remove_idea_vote_idea_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='votes',
            new_name='likes',
        ),
    ]
