# Generated by Django 4.1 on 2023-05-15 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0030_rename_votes_idea_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
