# Generated by Django 4.1 on 2023-05-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0031_remove_idea_likes_idea_liked_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
    ]
