# Generated by Django 4.1 on 2023-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0032_rename_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
