# Generated by Django 4.1 on 2023-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potbs', '0033_idea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
